"use strict";

export const catalogue = [
  {
    id: 12334495,
    title: "Jorgan beach",
    img: ["/beach-01.png", "/beach-02.png", "/beach-03.png", "/beach-04.png"],
    address: "jorgan beach",
    city: "delta",
    distance: 43,
    available: "Apr 7 - 12",
    price: "10,000",
    rating: 4.83,
    url: "#",
    tags: ["beach", "jorgan", "delta"],
  },
  {
    title: "Della beach Hotel",
    img: [
      "/resort-01.png",
      "/resort-02.png",
      "/resort-03.png",
      "/resort-04.png",
    ],
    distance: 53,
    address: "della beach",
    city: "delta",
    available: "May 6 - 11",
    price: "25,000",
    rating: 4.95,
    url: "#",
    tags: ["beach", "della", "hotel", "delta"],
  },
  {
    id: 12334495,
    title: "Jorgan beach",
    img: ["/beach-01.png", "/beach-02.png", "/beach-03.png", "/beach-04.png"],
    address: "jorgan beach",
    city: "delta",
    distance: 43,
    available: "Apr 7 - 12",
    price: "10,000",
    rating: 4.83,
    url: "#",
    tags: ["beach", "jorgan", "delta"],
  },
  {
    title: "Della beach Hotel",
    img: [
      "/resort-01.png",
      "/resort-02.png",
      "/resort-03.png",
      "/resort-04.png",
    ],
    distance: 53,
    address: "della beach",
    city: "delta",
    available: "May 6 - 11",
    price: "25,000",
    rating: 4.95,
    url: "#",
    tags: ["beach", "della", "hotel", "delta"],
  },
  {
    id: 12334495,
    title: "Jorgan beach",
    img: ["/beach-01.png", "/beach-02.png", "/beach-03.png", "/beach-04.png"],
    address: "jorgan beach",
    city: "delta",
    distance: 43,
    available: "Apr 7 - 12",
    price: "10,000",
    rating: 4.83,
    url: "#",
    tags: ["beach", "jorgan", "delta"],
  },
  {
    title: "Della beach Hotel",
    img: [
      "/resort-01.png",
      "/resort-02.png",
      "/resort-03.png",
      "/resort-04.png",
    ],
    distance: 53,
    address: "della beach",
    city: "delta",
    available: "May 6 - 11",
    price: "25,000",
    rating: 4.95,
    url: "#",
    tags: ["beach", "della", "hotel", "delta"],
  },
  {
    id: 12334495,
    title: "Jorgan beach",
    img: ["/beach-01.png", "/beach-02.png", "/beach-03.png", "/beach-04.png"],
    address: "jorgan beach",
    city: "delta",
    distance: 43,
    available: "Apr 7 - 12",
    price: "10,000",
    rating: 4.83,
    url: "#",
    tags: ["beach", "jorgan", "delta"],
  },
  {
    title: "Della beach Hotel",
    img: [
      "/resort-01.png",
      "/resort-02.png",
      "/resort-03.png",
      "/resort-04.png",
    ],
    distance: 53,
    address: "della beach",
    city: "delta",
    available: "May 6 - 11",
    price: "25,000",
    rating: 4.95,
    url: "#",
    tags: ["beach", "della", "hotel", "delta"],
  },
];